spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/development_and_operation_of_secure_automated_systems
    driverClassName: org.postgresql.Driver
    username: development-and-operation-of-secure-automated-systems
    password: development-and-operation-of-secure-automated-systems_psw
  liquibase:
    enabled: true
    change-log: classpath:development-and-operation-of-secure-automated-systems-db.yaml
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
    show-sql: true
    open-in-view: false
  logging:
    level:
      org:
        hibernate:
          type: trace